### ISSUE TITLE
Desktop Client Scaling Issue Between Different Displays

### ISSUE THREAD

**Issue by harry71019** [iwalton3/jellyfin-mpv-shim#51] opened 2020-04-09 22:40 UTC
**Describe the bug**
The UI breaks when changing the client to display on different displays (with different UI scaling in Windows display settings)

**To Reproduce**
1. Use a multi monitor setup
2. Have the two monitors set at different UI scaling
Monitor 1: 15.6" 1080p 125%
Monitor 2: 27" 1080p 100%
3. Drag the client between displays, the UI should break on one of the displays

**Expected behavior**
The UI should be able to adapt to different UI scaling in Windows.

**Screenshots**
![image](https://user-images.githubusercontent.com/59645782/78946514-e7240c00-7a90-11ea-87b5-24109b97bc2c.png)
(You can see that the elements show the mouse hovering over the library title "TV Shows", despite the mouse location being at the spot just above the block of Pocahontas)

Recorded Behavior (link to YouTube video)
https://youtu.be/znlHBEwa4dE

**Desktop (please complete the following information):**
Currently using version 10.5.3. Have tried 10.5.4 and 10.5.6 with the same results.

**Error Messages**
No error is shown

**Comment by iwalton3** [comment] 2020-04-09 22:51
Looks like an issue with CEF. Although that says it is resolved so I will have to look into this more.

https://github.com/r0x0r/pywebview/issues/331

**Comment by harry71019** [comment] 2020-04-10 01:29
Looking at that issue and this link mentioned in the issue
[]((https://stackoverflow.com/questions/55855723/how-to-stop-html-rendering-twice-in-the-same-window-on-hi-dpi-screens-using-cefp/55869426#55869426))
Using "Override high DPI scaling behavior" on run-desktop.exe solves the problem for now

**Comment by iwalton3** [comment] 2020-04-10 02:29
I think I have a fix. Please do the following:
 - Please undo the manual change that you made (this is important because it is a registry key that persists across reinstalls). 
 - Confirm the issue is present on the current version.
 - Uninstall the current version.
 - Install and test this test version: https://iwalton.com/ushare/jellyfin-mpv-desktop_test51_installer.exe

**Comment by harry71019** [comment] 2020-04-10 12:05
I have tested the new version and it looks to be working fine. I also tried quickly rescaling the window and dragging it back and forth between the two monitors and no crashes occurred.

**Comment by iwalton3** [comment] 2020-04-10 13:02
Ok. This fix will be in the next release. You can use the test release until then.

**Closed** 2020-04-10 13:02 UTC
