### ISSUE TITLE
mpv shim incorrectly reports "Stopped at 0 ms" when playing to completion.

### ISSUE THREAD

**Issue by lmaonator** [iwalton3/jellyfin-mpv-shim#170] opened 2021-03-12 21:10 UTC
When playing files to the end, playback stop is reported with 0ms played.
I noticed this while messing around with a plugin to report playback status to a website, similar to the Trakt plugin.
In the plugin when PlaybackStopped event is fired the PlaybackStopEventArgs also report PlayedToCompletion = false and PlaybackPositionTicks = 0.

**Example Jellyfin server logs playing to completion:**
[2021-03-11 22:55:07.962 +01:00] [INF] Profile: "Jellyfin MPV Shim", Path: "snipsnip.mkv", isEligibleForDirectPlay: False, isEligibleForDirectStream: True
[2021-03-11 22:55:09.237 +01:00] [INF] Playback Started
[2021-03-11 23:40:22.668 +01:00] [INF] Playback stopped reported by app "Jellyfin MPV Shim" "1.8.1" playing "Done". Stopped at "0" ms
[2021-03-11 23:40:22.796 +01:00] [INF] Playback Stopped
[2021-03-11 23:40:22.797 +01:00] [INF] Item Not fully played. Tell trakt.tv we are no longer watching but don't scrobble

The last line here is from the Trakt plugin, it also thinks it wasn't fully played and doesn't explicitly scrobble (the plugin still ends up working most of the time somehow, presumably the trakt website keeps track of runtime and marks played on its own when enough time passed)

On the other hand, it works fine when I end playback by pressing "q" 30 seconds before end (when credits start).
**Jellyfin server log when canceled manually short time before completion:**
[2021-03-11 22:09:14.045 +01:00] [INF] Profile: "Jellyfin MPV Shim", Path: "snipsnip.mkv", isEligibleForDirectPlay: False, isEligibleForDirectStream: True
[2021-03-11 22:09:14.596 +01:00] [INF] Playback Started
[2021-03-11 22:51:23.238 +01:00] [INF] Playback stopped reported by app "Jellyfin MPV Shim" "1.8.1" playing "Railroad Men". Stopped at "2549088" ms
[2021-03-11 22:51:23.343 +01:00] [INF] Playback Stopped
[2021-03-11 22:51:23.343 +01:00] [INF] Item is played. Scrobble

Last line again the Trakt plugin, this time everything works as expected and the episode is scrobbled.

Files are played through NFS share with direct_paths: true 

I don't see anything about stop time in the mpv-shim logs so I haven't saved them.

**For reference, stopped at is correctly reported by the Jellyfin Web player:**
[2021-03-12 22:01:49.222 +01:00] [INF] Playback stopped reported by app "Jellyfin Web" "10.7.0" playing "Snipped". Stopped at "1421002" ms
This particular episode is 23min 41sec long, so the 1421002ms are accurate.

**To Reproduce**
1. Play file to end
2. Stopped at reported as "0" ms and plugins relying on PlaybackStopped event fail to identify complete playback

**Expected behavior**
"Stopped at"/PlaybackPositionTicks should be reported as the same as the files runtime when played to completion.
I'm not sure exactly how PlayedToCompletion in PlaybackProgressEventArgs is determined by jellyfin, but if that is supposed to be sent by the player, mpv-shim in this case, then it should be also set to true.

**Setup:**
Jellyfin 10.7 running on Debian 10, installed through apt
jellyfin-mpv-shim 1.8.1 on Ubuntu 20.04, casting to it through the jellyfin web ui
direct_paths: true with NFS share

**Comment by iwalton3** [comment] 2021-03-12 22:07
I'll bet that the problem is the player's playback_time becomes null when the playback finishes, but this isn't handled and defaults to zero to avoid an exception.

**Comment by iwalton3** [comment] 2021-03-12 22:41
I have confirmed and fixed the issue. It will be in the next release.

**Closed by iwalton3** 2021-03-12 22:41 UTC
