### ISSUE TITLE
Always Transcode + Transcode to H265 should ask VideoCodec h265,hevc only

### ISSUE THREAD

**Issue by Videl** [iwalton3/jellyfin-mpv-shim#72] opened 2020-06-03 20:43 UTC
Hello,

When I set preferences "Always Transcode" and "Transcode to H265" to true, I believe mpv-shm should ask for h265 and hevc encodings only.

Currently, it sends the following:

* http://server/videos/some_id/hls1/main/28.ts?DeviceId=*id*&MediaSourceId=*id*&VideoCodec=h265,hevc,h264,mpeg4,mpeg2video&AudioCodec=aac,mp3,ac3,opus,flac,vorbis&AudioStreamIndex=1&VideoBitrate=19616000&AudioBitrate=384000&PlaySessionId=*id*&api_key=*key*&SubtitleMethod=Encode&TranscodingMaxAudioChannels=6&RequireAvc=false&Tag=*tag*&SegmentContainer=ts&BreakOnNonKeyFrames=False&TranscodeReasons=ContainerNotSupported,VideoCodecNotSupported,AudioCodecNotSupported

The interesting part is: **VideoCodec=h265,hevc,h264,mpeg4,mpeg2video**
Shouldn't that be VideoCodec=h265,hevc?
Currently, Jellyfin scans the list of VideoCodec (in variable ``state.SupportedVideoCodecs``) and check if the source codec is in the target codecs. If it is, it will copy the video and not transcode.

Relevant code in Jellyfin:

https://github.com/jellyfin/jellyfin/blob/c31b2798a521e6bfe7c6b078306a1b2244c0ea93/MediaBrowser.Controller/MediaEncoding/EncodingHelper.cs#L987-L992

**To Reproduce**
1. Start a video that's not in h265
2. Ask for h265 transcoding through the options *Always Transcode* and *Transcode to H265*

**Desktop (please complete the following information):**
 - OS: Windows
 - Version last released

Kindest regards

**Comment by iwalton3** [comment] 2020-06-03 21:57
So the problem here is Jellyfin really tries to avoid transcoding, so it will transcode even if I declare "Direct Play" as unsupported. (Which is what `always_transcode` does.)

The `transcode_to_h265` declares hevc as a *preferred* codec (usually it is disabled to prevent overloading servers), but it still allows any other codecs to be used by the server. (I would like to keep it this way so that if Jellyfin later adds the ability to disable hevc transcoding on the server, it will gracefully fall back, for instance if a user uses multiple different servers.)

What does work is setting the bandwidth. So if your server or client only has so much bandwidth, you can ensure that the player achieves the best quality within that limit. That is where preferring hevc as a transcoding format was intended to help, as it can double the image quality. (If software encoding is used. Encoding quality from nvenc may be similar to h264 unless you have a Turing graphics card, as that is needed for B-frame encoding.)

**Comment by Videl** [comment] 2020-06-04 10:20
Where is the param for the unsupported "Direct Play"? Is it in the **TranscodeReasons=ContainerNotSupported,VideoCodecNotSupported,AudioCodecNotSupported** part?

**Comment by iwalton3** [comment] 2020-06-07 13:50
The TranscodeReasons is actually from the Jellyfin server. The way the player works is I declare a supported profile, and then Jellyfin actually sends me a playback URL and if needed any external subtitle URLs to also load.

**Comment by iwalton3** [comment] 2020-08-09 20:32
Is there a need to force hevc for all videos, including by requiring a transcode, or is the current bandwidth-based approach good enough? HEVC transcoding in Jellyfin creates a tremendous load on the server and can frequently results in worse video quality than the original files (due to using a fast encoding profile).

**Comment by Videl** [comment] 2020-08-10 18:04
By all measures I am not an encoding expert :)
We noticed that issue when testing a graphical card with the option "Always Transcode".
I'd say the bandwith-based approach is enough. Maybe removing the option "Always Transcode" until Jellyfin understands the "Direct Play not supported"? 
Shall I close this issue?

**Comment by iwalton3** [comment] 2020-08-10 21:30
I’ll rename the option to “disable direct play” in the documentation and close the issue. It is still useful for constraining the video playback options.

**Comment by iwalton3** [comment] 2020-08-10 22:10
Ok I've made the change.

**Closed by iwalton3** 2020-08-10 22:10 UTC
Labels: enhancement
