### ISSUE TITLE
Enable Keyboard Media Keys

### ISSUE THREAD

**Issue by joytrekker** [iwalton3/jellyfin-mpv-shim#11] opened 2020-01-28 07:55 UTC
I'm not sure if this is by design or just a bug. Keyboard Media Keys Next and Previous no longer work when using jellyfin-mpv-shim. 

I can use the keys in chrome with jellyfin or in mpv stand alone.  I know the bindings "< + Shift" and "> + Shift" for Previous and Next and they work . Maybe these custom bindings are overriding the Media Keys?

**Comment by iwalton3** [comment] 2020-01-28 12:04
That is exactly what the issue is. Media keys are not bound and bindings for navigation are overrides.

**Comment by iwalton3** [comment] 2020-01-28 14:46
This has been fixed and will be released with the next update.

**Comment by iwalton3** [comment] 2020-01-30 16:27
This has been released in v1.3.1.

**Comment by joytrekker** [comment] 2020-01-30 23:13
I just tried release v1.3.1. However the media bindings don't work for windows.

**Comment by iwalton3** [comment] 2020-01-31 00:21
I think the NEXT and PREV bindings are what is used on Windows. Does this build work? https://iwalton.com/ushare/jellyfin-mpv-shim-test2.exe

**Comment by joytrekker** [comment] 2020-01-31 00:50
No it didn't work for me.  I think windows uses it own codes. https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes

**Comment by iwalton3** [comment] 2020-01-31 00:57
So I am testing this in a VM, which means the media keys aren't even seen by MPV.
Could you tell me what appears when you press the media keys?

Download mpv.exe: https://sourceforge.net/projects/mpv-player-windows/files/64bit/mpv-x86_64-20200126-git-ae0520c.7z/download
Run this in a command line: `mpv.exe --player-operation-mode=pseudo-gui --input-test`

Then send me what key codes it is using. (Key [Key code] is bound to...)

**Comment by joytrekker** [comment] 2020-01-31 01:09
OK I just tested with mpv and it is reporting NEXT, PREV 
I also get PLAYPAUSE and STOP for other two.

**Comment by iwalton3** [comment] 2020-01-31 02:12
Thanks for the help. It turns out there was an option that I had to enable for MPV to capture media keys on Windows. The latest release (1.3.2) should work, I tested it with an AutoHotKey script on Windows 10.

**Closed by iwalton3** 2020-01-31 02:12 UTC

**Comment by joytrekker** [comment] 2020-01-31 02:42
Ahh I see. It works good now. Thanks
