### ISSUE TITLE
Borderless Fullscreen

### ISSUE THREAD

**Issue by leaderdog** [iwalton3/jellyfin-mpv-shim#37] opened 2020-03-31 22:05 UTC
I tried this out on my windows 10 htpc.  The way I have plex setup is, windows boots and it goes directly into plex and proceed as normal.

When I load Jellyfin I cannot get it to be borderless fullscreen.  There is always a border.  If I do the windows key + up arrow, it resizes the window and I lose a good portion of the screen because it is hidden.  It's a 4k tv that I do 150% scaling, however it didn't matter with scaling off it still sent 1/4 or so of the picture off screen.  (this is the menu not the actual video player, the player works great).

I apologize if it's just my lack of knowledge, but is there some way to make the program itself full screen borderless?  The 3 windows min max x is always visible in the top right.

Thanks for any help,

windows 10 (1909)
version 1.5.4

**Comment by iwalton3** [comment] 2020-03-31 23:27
This has been added and will be in the next release.
You can enable fullscreen by editing the config file: `%appdata%\jellyfin-mpv-shim\conf.json`. Set `desktop_fullscreen` to `true`.

You can verify/use the fix prior to release with this dev build: https://iwalton.com/ushare/jellyfin-mpv-desktop_test_issue37.exe

**Comment by leaderdog** [comment] 2020-03-31 23:59
That looks Much better!

Although, two small issues.

In tv mode (didn't test in desktop mode)

1) The hamburger menu (3 lines) just makes the screen fade a bit, none of the menu options show up.
2) and this one's pretty important.  It's in full screen mode and always on top mode.  So if you alt+tab to another window you won't see it, it's always hidden even task manager wasn't visible.  The only way I could close it was to hold alt+tab, continue holding alt and then click the x in the tab menu.  As well as there is no way to exit the program except what I just mentioned. :)

A menu option to exit may be necessary.  Also the next ticket I would make (but I'll mention it here) is a switch user option.  Preferably one without requiring a password considering multiple people are going to use this without a keyboard.

Again, this could be my lack of knowledge of jellyfin.  In the browser version I couldn't find a way to switch users either.  So I'm assuming that's an oversight on their part.  But in the browser version in the hamburger menu there is a sign out option. An exit option would be great and it would be nice to have a switch user option and well another screen to select users.  I currently have 2 users set up but the only way currently is to sign out then type in the new user and password.  Not great when just using a remote :)

**Comment by iwalton3** [comment] 2020-04-01 00:01
The user switching issue should be logged against https://github.com/jellyfin/jellyfin-web, as that is the upstream web client project.

**Comment by leaderdog** [comment] 2020-04-01 00:16
You're using their infrastructure for desktop client?  
I can see why you'd need to login via a web client.  But desktop is different for htpc use.

**Comment by iwalton3** [comment] 2020-04-01 00:36
> You're using their infrastructure for desktop client?

Yes, I'm embedding the web client currently with a fairly minimal patch set to allow it to connect to the MPV system. As far as I know, fast user switching isn't available in the web client, but there is a feature request.

Adding a feature such as user switching isn't something I would really want to do right now. The web client is [due to be re-written in something more manageable](https://github.com/jellyfin/jellyfin-web/issues/889), as it is currently a headache for me to understand. If upstream adds it though it would be easy for me to update the client to support it. I will probably get more involved with web client development in the future.

As for closing the application, in fullscreen you should be able to use ALT+F4. I wasn't able to reproduce the issue with the hamburger menu.

It looks like an upstream fix for the always-on-top issue is in-progress with the library that provides the web interface, so that should be available when they release. https://github.com/r0x0r/pywebview/issues/476

**Comment by leaderdog** [comment] 2020-04-01 00:48
Sounds good. 

Right Alt+F4 forgot about that.  I'd have to program that to a button on the remote... but I guess I'd have to bring the keyboard out to work on anything at that point anyways, so may not be necessary.  But unfortunately, without a switch user option it can't replace Plex yet.  Unless I wanted to use Kodi again, which I kind of don't haha.

Thanks, and I appreciate the help!

**Comment by iwalton3** [comment] 2020-08-09 20:53
A lot has changed in the web client since this issue was opened. Please re-open this if the issue with TV mode is still present and isn't present in TV mode opened through a regular web browser. 

Same with the issue with the fullscreen window opening with always-on-top active. From my reading of the latest PyWebView source code, it looks like that should also be fixed [based on the upstream code changes](https://github.com/r0x0r/pywebview/commit/e956b3e635f7810eef4e7961d75b4ec4578571ce).

User switching isn't something I can really control in the Web Client (remember that is an upstream project), but it is worth noting that if the usage is on your LAN, you can turn on the Easy PIN Code option to make switching easier. (Just use the PIN Code instead of a password.)

**Closed by iwalton3** 2020-08-09 20:53 UTC
Labels: Desktop Mode
